title: Bora Ilci - DevOps Engineer
email: your-email@example.com
description: >-
  A personal portfolio showcasing DevOps projects, automation workflows, 
  and cloud infrastructure expertise.
baseurl: "/gh-deployment-workflow"
url: "https://borailci.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - tasks.md
